### ISSUE TITLE
Can't open included iuml when running Antora

### ISSUE THREAD

**Issue by jvmlet** [ggrossetie/asciidoctor-kroki#288]
I'm generating the docs with Antora , `myDiagramm.puml` looks like below :

````yml
@startuml
!include globals.iuml
....

@enduml
````

and `globals.iuml` resides in the same folder as `myDiagramm.puml`, which is `partials/uml`

When executing Antora, I'm getting
```
Skipping preprocessing of PlantUML include, because reading the referenced local file 'globals.iuml' caused an error:
Error: ENOENT: no such file or directory, open 'globals.iuml'
```

**Comment by Mogztter** [comment]
> and globals.iuml resides in the same folder as myDiagramm.puml, which is partials/uml

Technically, this is not the correct location.
From the Antora documentation:

> Partials are resources that contain content snippets, such as common descriptions, terminology, or reference tables, that you plan to reuse in one or more pages. **Partials are saved as AsciiDoc source files (.adoc) and stored in a partials directory.**

https://docs.antora.org/antora/2.3/partials-directory/#partials

I think you should store them in `examples`: https://docs.antora.org/antora/2.3/examples-directory/

Anyway, could you please share how do you reference `myDiagramm.puml` in your AsciiDoc file?

**Comment by Mogztter** [comment]
It won't work if you are referencing your diagram as follows:


**modules/ROOT/examples/hello.puml**
```puml
@startuml
!include globals.iuml

Guillaume -> Alexander : Hello!
@enduml

```

**modules/ROOT/examples/globals.iuml**
```puml
skinparam monochrome true
skinparam ranksep 20
skinparam dpi 150
skinparam arrowThickness 0.7
skinparam packageTitleAlignment left
skinparam usecaseBorderThickness 0.4
skinparam defaultFontSize 12
skinparam rectangleBorderThickness 1
```

```adoc
[plantuml]
----
include::example$hello.puml[]
----

**Comment by jvmlet** [comment]
Thanks for your replay, @Mogztter 
I can't use alternative approach , because `hello.puml` won't be rendered by IDE
Setting `kroki-plantuml-include-paths`  also  fails with the same error :
````
asciidoc:
  attributes:
    kroki-plantuml-include-paths: './docs/modules/ROOT/examples'
````
I'm using `plantuml::{examplesdir}/myDiagramm.puml[]` from the `adoc` file
Both `myDiagramm.puml` and `globals.iuml` are under  `ROOT/examples` dir

**Comment by Mogztter** [comment]
> Setting kroki-plantuml-include-paths also fails with the same error :

The value depends on your directory structure. In my case, I'm running `antora` at the root of the project and I have the following directory structure:

```
docs
├── antora.yml
└── modules
    └── ROOT
        └─── examples
            ├── globals.iuml
            └── hello.puml
```

> I'm using plantuml::{examplesdir}/myDiagramm.puml[] from the adoc file

The problem is that `{examplesdir}/myDiagramm.puml` (or `example$myDiagramm.puml`) relies on a virtual filesystem: https://docs.antora.org/antora/2.3/organize-content-files/#antoras-virtual-filesystem

I don't know if we can resolve `!include globals.iuml`, we might be able to prefix `globals.iuml` with `example$` and ask Antora to resolve it... Can't make any promise but I will take a closer look.

What is certain is that `include::example$hello.puml[]` won't work, you need to use `plantuml::{examplesdir}/hello.puml[]`.

**Comment by wouter-veeken** [comment]
I'm struggling with a similar issue, although I'm using Asciidoctor JS in Gatsby and not Antora. I can't figure out what `kroki-plantuml-include-paths` considers to be the root folder. This is my file/folder structure:

```
.
├──docs/
   ├──diagrams/
      └──stylesheet.puml
      └──diagram.puml
   └──productName/
      └──document.adoc
├──site/
      └──gatsby-config.js
```

In `gatsby-config.js`, I'm defining this:

```
        attributes: {
          ...
          "kroki-plantuml-include-paths": "./docs/diagrams/",
          "kroki-plantuml-include": "puml-stylesheet.puml"
          ...
        },
```

But I keep getting:
```
warn Skipping preprocessing of PlantUML include, because reading the referenced local file 'puml-stylesheet.puml' caused an error:
Error: ENOENT: no such file or directory, open 'puml-stylesheet.puml'
```

I've verified that it works with an absolute path (i.e. `/Users/myName/git_tree/etc`) but none of the relative paths I've tried work. 

Any guidance? Thanks in advance!

**Comment by yann-soubeyrand** [comment]
Hello,
I may be wrong, but the workaround (setting `kroki-plantuml-include-paths` attribute) doesn’t seem to work for Structurizr diagrams `!include` directive. Does it?

**Comment by yann-soubeyrand** [comment]
If I understand the code correctly, I’d say that `include` preprocessing isn’t done for Structurizr diagrams, right?
https://github.com/Mogztter/asciidoctor-kroki/blob/38715518c590222e033cb39a152d0ad18ae51704/src/asciidoctor-kroki.js#L73-L84

**Comment by Mogztter** [comment]
Hello Yann,

Yes that's correct.
For now, we preprocess PlantUML and VegaLite diagrams (to some extent).

The attribute `kroki-plantuml-include-paths` is specific for PlantUML diagrams and won't have any effect on Structurizr diagrams.

**Comment by jay-blanc** [comment]
Hello,

I'm trying to get diagrams with "**plantuml fragments (separated .iuml files)**" through Antora.
I tried the workaround setting the "**kroki-plantuml-include-paths**" attribute, specifying a relative path but I failed generating the documentation.
In order to explain what I did, I created repositories in order to expose the issue I get which is logged during the Antora generation.

Here is the error I got during the generation process :

```
$ npx antora generate --stacktrace --log-level=all --fetch antora-playbook.yml
[clone] https://github.com/jay-blanc/antora-doc-asciidoc.git                 [###############################################################################################################################]
[clone] https://github.com/jay-blanc/antora-doc-asciidoc-plantuml-simple.git [###############################################################################################################################]
[clone] https://github.com/jay-blanc/antora-doc-asciidoc-plantuml-iuml.git   [###############################################################################################################################]
[14:37:29.095] INFO (asciidoctor): Skipping preprocessing of PlantUML include, because reading the referenced local file 'class_a.iuml' caused an error:
Error: ENOENT: no such file or directory, open 'class_a.iuml'
    file: modules/ROOT/pages/diag-class.adoc
    source: https://github.com/jay-blanc/antora-doc-asciidoc-plantuml-iuml.git (branch: master)
[14:37:29.100] INFO (asciidoctor): Skipping preprocessing of PlantUML include, because reading the referenced local file 'class_b.iuml' caused an error:
Error: ENOENT: no such file or directory, open 'class_b.iuml'
    file: modules/ROOT/pages/diag-class.adoc
    source: https://github.com/jay-blanc/antora-doc-asciidoc-plantuml-iuml.git (branch: master)
Site generation complete!
```

As shown in the log above, the repositories built to expose the issue are the following :

- https://github.com/jay-blanc/antora-doc-asciidoc : simple Asciidoc documentation of a component "A"
- https://github.com/jay-blanc/antora-doc-asciidoc-plantuml-simple : Asciidoc documentation with a simple standalone PlantUML diagram
- https://github.com/jay-blanc/antora-doc-asciidoc-plantuml-iuml : Asciidoc documentation with a PlantUML diagram including PlantUML fragments (iuml files defining classes)
- https://github.com/jay-blanc/antora-playbook : Playbook building the whole documentation of the 3 components

This follows the architecture below :

![poc-antora-archi](https://github.com/ggrossetie/asciidoctor-kroki/assets/61079940/187e34fb-f7f8-456d-98a3-ccdcf4bb8d11)

And here is the result I got after building the documentation :

![poc-antora-resultat](https://github.com/ggrossetie/asciidoctor-kroki/assets/61079940/0eb664a4-fa64-4a8c-b2b9-b6671bb1e1eb)

Could you please tell me what I did wrong / if what I want to do is possible ?

Thank you :)
