### ISSUE TITLE
Error when I try to convert the documentation as PDF

### ISSUE THREAD

**Issue by Ajedrel** [ggrossetie/asciidoctor-kroki#412]
When I click in Generate and open documentation as PDF I got the following error:
Error 5000 occurred at Wovalab_lib_AsciiDoctor.lvlib:Rendering Failed--error.vi
Documentation.adoc: Failed to load AsciiDoc document - Failed to open TCP connection to kroki.io:443 (getaddrinfo: Host desconocido. )
  Use --trace to show backtrace

Complete call chain:
     Wovalab_lib_AsciiDoctor.lvlib:Rendering Failed--error.vi
     Wovalab_lib_AsciiDoctor.lvlib:Render Adoc File.vi
     Final Doc Rendering.vi
     End Of Generation--dialog .vi
     Generate Project Documentation.vi

**Comment by ggrossetie** [comment]
You should contact/ask Wovalab but the error indicates that the "process" doesn't have access to kroki.io. Probably a network issue. Possible cause is a firewall/corporate proxy or bad DNS. 

Since it seems unrelated to the Asciidoctor Kroki extension itself I'm closing.

It would also be helpful to obtain the backtrace using `--trace`.
